name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore library dependencies
      run: dotnet restore AOEMods.Essence
    - name: Build library
      run: dotnet build AOEMods.Essence --no-restore
      
    - name: Restore library tests dependencies
      run: dotnet restore AOEMods.Essence.Test
    - name: Build library tests
      run: dotnet build AOEMods.Essence.Test --no-restore
    - name: Run library tests
      run: dotnet test AOEMods.Essence.Test --no-build --verbosity normal

    - name: Restore CLI dependencies
      run: dotnet restore AOEMods.Essence.CLI
    - name: Build CLI
      run: dotnet build AOEMods.Essence.CLI --no-restore

    - name: Restore CLI tests dependencies
      run: dotnet restore AOEMods.Essence.CLI.Test
    - name: Build CLI tests
      run: dotnet build AOEMods.Essence.CLI.Test --no-restore
    - name: Run CLI tests
      run: dotnet test AOEMods.Essence.CLI.Test --no-build --verbosity normal
      
